export const ClothAccessoryList=()=>({
  HeadWear: [
    { id: 0, value: 'baseballcap', label: 'Baseball Cap' },
    { id: 1, value: 'beanie', label: 'Beanie' },
    { id: 2, value: 'fedora', label: 'Fedora' },
    { id: 3, value: 'bucket_hat', label: 'Bucket Hat' },
    { id: 4, value: 'beret', label: 'Beret' },
    { id: 5, value: 'cowboy_hat', label: 'Cowboy Hat' },
    { id: 6, value: 'snapback', label: 'Snapback' },
    { id: 7, value: 'visor', label: 'Visor' },
    { id: 8, value: 'sunhat', label: 'Sun Hat' },
    { id: 9, value: 'trilby', label: 'Trilby' },
    { id: 10, value: 'flat_cap', label: 'Flat Cap' },
    { id: 11, value: 'boater', label: 'Boater Hat' },
    { id: 12, value: 'panama_hat', label: 'Panama Hat' },
    { id: 13, value: 'headband', label: 'Headband' },
    { id: 14, value: 'turban', label: 'Turban' },
    { id: 15, value: 'helmet', label: 'Helmet' },
    { id: 16, value: 'hood', label: 'Hood' },
    { id: 17, value: 'skimask', label: 'Ski Mask' },
    { id: 18, value: 'top_hat', label: 'Top Hat' },
    { id: 19, value: 'bowler_hat', label: 'Bowler Hat' }
  ],
  BodyWear: [
    { id: 1, value: 'tshirt', label: 'T-Shirt' },
    { id: 2, value: 'shirt', label: 'Shirt' },
    { id: 3, value: 'hoodie', label: 'Hoodie' },
    { id: 4, value: 'jacket', label: 'Jacket' },
    { id: 5, value: 'sweater', label: 'Sweater' },
    { id: 6, value: 'coat', label: 'Coat' },
    { id: 7, value: 'tanktop', label: 'Tank Top' },
    { id: 8, value: 'vest', label: 'Vest' },
    { id: 9, value: 'blazer', label: 'Blazer' },
    { id: 10, value: 'cardigan', label: 'Cardigan' },
    { id: 11, value: 'polo', label: 'Polo Shirt' },
    { id: 12, value: 'longsleeve', label: 'Long Sleeve Shirt' },
    { id: 13, value: 'crop_top', label: 'Crop Top' },
    { id: 14, value: 'sweatshirt', label: 'Sweatshirt' },
    { id: 15, value: 'windbreaker', label: 'Windbreaker' },
    { id: 16, value: 'anorak', label: 'Anorak' },
    { id: 17, value: 'kimono', label: 'Kimono' },
    { id: 18, value: 'puffer_jacket', label: 'Puffer Jacket' },
    { id: 19, value: 'tunic', label: 'Tunic' },
    { id: 20, value: 'bomber_jacket', label: 'Bomber Jacket' }
  ],
  HandWear: [
    { id: 1, value: 'gloves', label: 'Gloves' },
    { id: 2, value: 'mittens', label: 'Mittens' },
    { id: 3, value: 'leather_gloves', label: 'Leather Gloves' },
    { id: 4, value: 'wool_gloves', label: 'Wool Gloves' },
    { id: 5, value: 'fingerless_gloves', label: 'Fingerless Gloves' },
    { id: 6, value: 'driving_gloves', label: 'Driving Gloves' },
    { id: 7, value: 'cycling_gloves', label: 'Cycling Gloves' },
    { id: 8, value: 'ski_gloves', label: 'Ski Gloves' },
    { id: 9, value: 'gardening_gloves', label: 'Gardening Gloves' },
    { id: 10, value: 'rubber_gloves', label: 'Rubber Gloves' },
    { id: 11, value: 'latex_gloves', label: 'Latex Gloves' },
    { id: 12, value: 'nitrile_gloves', label: 'Nitrile Gloves' },
    { id: 13, value: 'mitts', label: 'Mitts' },
    { id: 14, value: 'opera_gloves', label: 'Opera Gloves' },
    { id: 15, value: 'work_gloves', label: 'Work Gloves' },
    { id: 16, value: 'boxing_gloves', label: 'Boxing Gloves' },
    { id: 17, value: 'gardener_mitts', label: 'Gardener Mitts' },
    { id: 18, value: 'thermal_gloves', label: 'Thermal Gloves' },
    { id: 19, value: 'driving_mitts', label: 'Driving Mitts' },
    { id: 20, value: 'sports_gloves', label: 'Sports Gloves' }
  ],
  LegWear: [
    { id: 1, value: 'jeans', label: 'Jeans' },
    { id: 2, value: 'chinos', label: 'Chinos' },
    { id: 3, value: 'shorts', label: 'Shorts' },
    { id: 4, value: 'cargo_pants', label: 'Cargo Pants' },
    { id: 5, value: 'leggings', label: 'Leggings' },
    { id: 6, value: 'sweatpants', label: 'Sweatpants' },
    { id: 7, value: 'track_pants', label: 'Track Pants' },
    { id: 8, value: 'khakis', label: 'Khakis' },
    { id: 9, value: 'tights', label: 'Tights' },
    { id: 10, value: 'capris', label: 'Capris' },
    { id: 11, value: 'dress_pants', label: 'Dress Pants' },
    { id: 12, value: 'corduroys', label: 'Corduroys' },
    { id: 13, value: 'overalls', label: 'Overalls' },
    { id: 14, value: 'joggers', label: 'Joggers' },
    { id: 15, value: 'skirt', label: 'Skirt' },
    { id: 16, value: 'culottes', label: 'Culottes' },
    { id: 17, value: 'palazzo_pants', label: 'Palazzo Pants' },
    { id: 18, value: 'bootcut_pants', label: 'Bootcut Pants' },
    { id: 19, value: 'jeggings', label: 'Jeggings' },
    { id: 20, value: 'short_shorts', label: 'Short Shorts' }
  ],
  FootWear: [
    { id: 1, value: 'sneakers', label: 'Sneakers' },
    { id: 2, value: 'boots', label: 'Boots' },
    { id: 3, value: 'sandals', label: 'Sandals' },
    { id: 4, value: 'flip_flops', label: 'Flip Flops' },
    { id: 5, value: 'loafers', label: 'Loafers' },
    { id: 6, value: 'oxfords', label: 'Oxfords' },
    { id: 7, value: 'derby_shoes', label: 'Derby Shoes' },
    { id: 8, value: 'brogues', label: 'Brogues' },
    { id: 9, value: 'heels', label: 'Heels' },
    { id: 10, value: 'wedges', label: 'Wedges' },
    { id: 11, value: 'moccasins', label: 'Moccasins' },
    { id: 12, value: 'espadrilles', label: 'Espadrilles' },
    { id: 13, value: 'clogs', label: 'Clogs' },
    { id: 14, value: 'slippers', label: 'Slippers' },
    { id: 15, value: 'ankle_boots', label: 'Ankle Boots' },
    { id: 16, value: 'chelsea_boots', label: 'Chelsea Boots' },
    { id: 17, value: 'rain_boots', label: 'Rain Boots' },
    { id: 18, value: 'hiking_boots', label: 'Hiking Boots' },
    { id: 19, value: 'trainers', label: 'Trainers' },
    { id: 20, value: 'basketball_shoes', label: 'Basketball Shoes' }
  ]
})
